# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "cons-f-dev"
client_id = "a933d5647dd636d6d33c9ed9bc9f1164"
application_url = "https://cons-f-dev.cpro-server.de"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_orders,read_orders"

[auth]
redirect_urls = [
  "https://cons-6a9dc71762e0.herokuapp.com/auth/callback",
  "https://cons-6a9dc71762e0.herokuapp.com/auth/shopify/callback",
  "https://cons-6a9dc71762e0.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "helge-test.myshopify.com"
